// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tewvbhwqhsqngfuzmsop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRld3ZiaHdxaHNxbmdmdXptc29wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzODA1NzMsImV4cCI6MjA1Njk1NjU3M30.6eJ9nU6X48fKOsDQ6yqFQCL0fMLQpqkyY5rVpG_p0uE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);